package co.techmagic.hr.presentation.ui;


public enum EditProfileFields {

    NONE,
    CHANGE_EMAIL,
    CHANGE_PASSWORD,
    CHANGE_FIRST_NAME,
    CHANGE_LAST_NAME,
    CHANGE_DATE_OF_BIRTH,
    CHANGE_SKYPE,
    CHANGE_PHONE,
    CHANGE_EMERGENCY_NUMBER,
    CHANGE_EMERGENCY_CONTACT,
    CHANGE_ROOM,
    CHANGE_CITY_OF_RELOCATION,
    CHANGE_PRESENTATION,
    CHANGE_DEPARTMENT,
    CHANGE_LEAD,
    CHANGE_FIRST_DAY,
    CHANGE_FIRST_DAY_IN_IT,
    CHANGE_TRIAL_PERIOD,
    CHANGE_PDP_LINK,
    CHANGE_ONE_TO_ONE_LINK,
    CHANGE_LAST_WORKING_DAY,
    CHANGE_REASON,
    CHANGE_COMMENTS
}
